### ISSUE TITLE
support for multiple language stopwords removal

### ISSUE THREAD

**Issue by jeffkayne** [artefactory/NLPretext#149]
When using STT apis, often you are returned a text that has some english words like "yes" even though the general language is, for example, french. Could we extrapolate the remove_stopwords function to remove stopwords from multiple languages?

**Comment by hugovasselin** [comment]
Hi Jeff, 

Thanks for your post. This can be done like this:
```
from nlpretext._utils.stopwords import get_stopwords
from nlpretext.token.preprocess import remove_stopwords

additional_stopwords_list = get_stopwords('en')
my_tokens_clean = remove_stopwords(my_tokens, lang='fr', custom_stopwords=additional_stopwords_list)
```

What we could do to make it more user friendly is to refacto the `remove_stopwords` function, making `lang` optional, such as: 

```
stopwords_list = get_stopwords('en') +  get_stopwords('fr') 
my_tokens_clean = remove_stopwords(my_tokens, custom_stopwords=stopwords_list)
```

What do you think?

**Comment by jeffkayne** [comment]
Hey Hugo, 

Thanks for the response - indeed these both work. I was thinking to make `lang` either a str or a list, but I think your first solution is more elegant as the logic of the function uses the specific language tokenizer. Also, there is often a primary language (in my case french), and the extra stopwords are the english ones.

I therefore don't think it's worth adding any changes ! 
Thanks
