### ISSUE TITLE
AttributeError 'module emoji has no attribute 'get_emoje_regexp'' is raised when calling function 'Preprocessor'

### ISSUE THREAD

**Issue by cheerchung** [artefactory/NLPretext#225]
## 🐛 Bug Report

AttributeError is raised when calling the function `Preprocessor`.
Description of error: `module 'emoji' has no attribute 'get_emoji_regexp'`
## 🔬 How To Reproduce

Just use the code example in the part of 'Usage --> default pipeline' by following 'README' doc.

### Code sample

```
from nlpretext import Preprocessor
text = "I just got the best dinner in my life @latourdargent !!! I  recommend 😀 #food #paris \n"
preprocessor = Preprocessor()
text = preprocessor.run(text)
print(text)
```
### Environment

* OS: macOS
* Python version: 3.7.13

### Screenshots

<img width="693" alt="image" src="https://user-images.githubusercontent.com/62287739/180783342-3db42890-5e65-491f-80c6-5fee7b4cbd2b.png">

## 📈 Expected behavior

This text should be preprocessed with default pipeline.

**Comment by cvzi** [comment]
The function `get_emoji_regexp` was [removed from the emoji module in version 2.0.0](https://carpedm20.github.io/emoji/docs/#regular-expression)
https://github.com/artefactory/NLPretext/blob/fa44f0ef825351b9710852f596c64935dd4455d8/nlpretext/_config/constants.py#L218

The last version to contain this function was `emoji==1.7.0`
