### ISSUE TITLE
AttributeError: module 'emoji' has no attribute 'get_emoji_regexp'

### ISSUE THREAD

**Issue by JayaRaghavendra** [artefactory/NLPretext#289]
## 🔬 How To Reproduce

1. ...

### Environment

* OS: [e.g. Linux / Windows / macOS]
* Python version, get it with:

```bash
python --version
```

**Comment by julesbertrand** [comment]
Hi, this issue was raised before and has been fixed. Please update NLPretext to the latest release (1.2.1) to fix it on your side.
